### ISSUE TITLE
Synthetic Training Data

### ISSUE THREAD

**Issue by shenqq377** [Jaraxxus-Me/VoxDet#2]
Dear authors,

Thanks for your excellent work for novel instance detection. We are working on training open-world detector with synthetic training data. The OWID dataset only contains 9691 instances not 9901 instances. Some of instances are not looked like an object, such as 7993. Could you please  upload a separate folder for objects?

**Comment by Jaraxxus-Me** [comment]
Hi, thanks for your interest in our work.
I just double-checked the OWID data, it indeed has only 9691 instances in the P1 folder, and it is what we have used for training VoxDet. This could be a typo in the paper.
I didn't carefully check all the instances in the dataset, they are just randomly drawn from ShapeNet and ABO datasets.
I think you may find this tool useful to generate your custom training set if you are unsatisfied with some instances:
https://github.com/Jaraxxus-Me/OWID-toolkit

**Comment by shenqq377** [comment]
Many thanks for your suggestion.
